# Generated by Django 3.2.5 on 2022-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
